### ISSUE TITLE
Code does not work if issuer contains spaces

### ISSUE THREAD

**Issue by julianlam** [julianlam/nodebb-plugin-2factor#10]
See #5

**Comment by Janus-SGN** [comment]
I'm not on my dev computer, but solution founded. I can't push the fix actually.

Old : 
```javascript
var otpUrl = "otpauth://totp/" + userslug + "@" + baseUrl + "?issuer=" + meta.config.title.replace(/\s/, '+') + "&secret=" + encodedKey + '&period=30',
```

New :
```javascript
var otpUrl = "otpauth://totp/" + userslug + "@" + baseUrl + "?issuer=" + meta.config.title.replace(/\s/, '+') + "&secret=" + encodedKey + '&period=30',
```

I just put ".replace(/\s/, '+')" after "meta.config.title".

Tested on iOS and Android, it works :)

**Comment by julianlam** [comment]
Would it work if you turned the spaces to `%20`?

**Comment by Janus-SGN** [comment]
I don't tested, but i think the urlencode understand it as character and not space.

**Comment by Janus-SGN** [comment]
Tryed, it work to.

**Comment by Janus-SGN** [comment]
Did I push on your branch or do I make a pull request ?

**Comment by julianlam** [comment]
You have collaborator access, so you can push to this branch.

**Comment by julianlam** [comment]
Let me know your npm username, so you can publish to npm as well.

**Comment by Janus-SGN** [comment]
I don't have npm username :s
