### ISSUE TITLE
Not working with Microsoft Authenticator

### ISSUE THREAD

**Issue by HunterGPlays** [julianlam/nodebb-plugin-2factor#13]
When I try to scan the code in, it says "The code you scanned does not contain valid account and key data."

My account name comes up in the field in the app however it has issues getting the secret key. I'm running the latest plugin (1.1.7) and nodebb version (0.9.3).

**Comment by Janus-SGN** [comment]
From Microsoft Support :  (Source : https://support.microsoft.com/en-us/kb/2935790 no available but available from [Google Cache](https://webcache.googleusercontent.com/search?q=cache:MwVBdVkw2CkJ:https://support.microsoft.com/en-us/kb/2935790+&cd=2&hl=fr&ct=clnk&gl=en) )

> This issue occurs if you're using the Microsoft Authenticator app instead of the Multi-Factor Authentication app. When you use work or school accounts (not Microsoft accounts) to sign in to Microsoft cloud services, you must use the Multi-Factor Authentication app. 

Solution from Microsoft : 

> Install the Multi-Factor Authentication app on your device. To download the app, use one of the following links, as appropriate for your situation:

[Multi-Factor Authentication for Windows Phone](http://www.windowsphone.com/en-us/store/app/multi-factor-auth/0a9691de-c0a1-44ee-ab96-6807f8322bd1)
[Multi-Factor Authentication for iPhone](https://itunes.apple.com/us/app/multi-factor-authentication/id475844606?mt=8)
[Multi-Factor Authentication for Android](https://play.google.com/store/apps/details?id=com.phonefactor.phonefactor) <- no more available on Play Store

**Comment by HunterGPlays** [comment]
Thanks, I'll try out Azure Authenticator.
