### ISSUE TITLE
Unable to generate backup codes.

### ISSUE THREAD

**Issue by GravzyIT** [julianlam/nodebb-plugin-2factor#17]
I've not been able to get the time to test this fully but since the update a few days ago I cannot generate backup codes.

**Comment by eldoreddler** [comment]
Can confirm this aswell. The button is there but does nothing when pressed. From my testing it affects NodeBB 1.1.2 but not NodeBB 1.1.0. Both installs where running the plugin at version 2.0.2.

**Comment by julianlam** [comment]
Well, that's annoying :smile: -- thanks for the report, guys.

**Comment by julianlam** [comment]
v2.1.0
