### ISSUE TITLE
QR Codes Invalid

### ISSUE THREAD

**Issue by cookieman768** [julianlam/nodebb-plugin-2factor#20]
When I attempt to scan the QR code with Authy or Google Authenticator on my iOS device it says invalid. Here's an example of the image generated that does not work: https://simplecraft.gyazo.com/04f762a292ea0387a22e976520d99d1c

**Comment by julianlam** [comment]
Can you try with FreeOTP?

**Comment by cookieman768** [comment]
@julianlam it scanned but nothing was added to the app's menu, there was no error in FreeOTP but the same error existed in Authy and Google Authenticator. Here's the QR that was generated: http://prntscr.com/czsn21

**Comment by dnkls** [comment]
the same eituation in ios(

**Comment by intralizee** [comment]
Using authy on iOS, I get the same error as well.

**Comment by julianlam** [comment]
For Christmas this year I wish for an iPhone so I can finally debug this 😦

**Comment by 0312birdzhang** [comment]
@julianlam 
Fixed https://github.com/julianlam/nodebb-plugin-2factor/pull/32
Please test it on android devices.

**Comment by julianlam** [comment]
Closed via #32
