### ISSUE TITLE
Unable to generate backup codes

### ISSUE THREAD

**Issue by GitPuffy** [julianlam/nodebb-plugin-2factor#25]
I believe this problem is back again.

Occurring on my NodeBB forum running `v1.4.5` as well as on community.nodebb.org

https://github.com/julianlam/nodebb-plugin-2factor/issues/17

**Comment by julianlam** [comment]
Hi there,

Unfortunately I cannot reproduce... our support forum is running latest NodeBB with the 2factor plugin and I just successfully generated backup codes for my account...

**Comment by GitPuffy** [comment]
I cannot get it to work with either Safari on OS X El Capitan or iSafari on OS 10.3.2. 

I'll investigate with Firefox when I have the opportune.

**Comment by GitPuffy** [comment]
Must be an issue with compatibility with Safari.  With Firefox on OS X El Capitan I was able to generate the backup codes.   Still does not work with Safari though.

**Comment by julianlam** [comment]
`Error: Syntax error, unrecognized expression: button[data-action="generateBackupCodes"`

**Comment by julianlam** [comment]
Odd, where'd the `]` go...

**Comment by julianlam** [comment]
v2.2.2
