### ISSUE TITLE
Chat viewable on 2FA Screen

### ISSUE THREAD

**Issue by nsuchy** [julianlam/nodebb-plugin-2factor#29]
As shown below you can access chats while on the 2FA Screen, this exposes some account information before being properly authenticated. Thoughts?

![1fn6ny2](https://user-images.githubusercontent.com/8227641/30944496-55c87fc8-a3c6-11e7-9737-398c5ba70218.png)

**Comment by julianlam** [comment]
Hi @nsuchy -- as designed the 2factor plugin denies access to **pages**, and chat is unfortunately separate from that (well, the **modal** is, not the chat page itself, and they share the same backend).

Looks like we'll have to add some additional hooks in to deny access to chat content, thanks for finding!
