### ISSUE TITLE
 Error: ENOENT: no such file or directory, open

### ISSUE THREAD

**Issue by danielperez9430** [julianlam/nodebb-plugin-2factor#33]
Missing translation "2factor:title"
Missing translation "2factor:title"
2018-03-02T23:44:27.257Z [3194] - [31merror[39m: /assets/templates/admin/plugins/2factor.js
 Error: ENOENT: no such file or directory, open '/var/www/NodeBB/build/public/templates/admin/plugins/2factor.tpl'
    at Error (native)
Missing translation "2factor:title"
Missing translation "2factor:title"
Missing translation "2factor:title"
Missing translation "2factor:title"
Missing translation "2factor:title"
Missing translation "2factor:title"

I used NodeBB v1.7.5.

**Comment by julianlam** [comment]
After installing and activating the plugin did you rebuild and restart NodeBB?

**Comment by danielperez9430** [comment]
@julianlam yes I fixed :) Now work
