### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by Viper61** [julianlam/nodebb-plugin-2factor#4]
Hello,
Could be great to add internationalization support for non english users.

**Comment by julianlam** [comment]
Sounds like a good idea! :+1:

**Comment by julianlam** [comment]
Have at it! :smile:

**Comment by Viper61** [comment]
Thanks !
But, it looks like the javascript part is locked in English? (user profile's menu, pop ups/confirmation messages)

**Comment by julianlam** [comment]
Hm, thanks for letting me know. Looks like I missed a few.

**Comment by julianlam** [comment]
Closed via 7b90291b40ce24613185f9b303a8f87024116902

**Comment by julianlam** [comment]
That above commit should cover client-side strings as well now.

**Comment by Janus-SGN** [comment]
Hello, 
the error message is always in English.

![image](https://cloud.githubusercontent.com/assets/4434864/9479962/4629a894-4b80-11e5-8e93-0e0d09497f32.png)

Is there any way to translate it to ?

**Comment by julianlam** [comment]
Thanks @Janus-SGN
