### ISSUE TITLE
Support webauthn

### ISSUE THREAD

**Issue by oplik0** [julianlam/nodebb-plugin-2factor#47]
[Webauthn](https://en.wikipedia.org/wiki/WebAuthn) is one of a components of FIDO2, a successor to u2f, that allows websites to use hardware authenticators as a second factor or even as the only factor (either passwordless or by storing residential keys even without the need for usernames).

Implementing it as a second factor here would allow for use of more secure and convenient hardware security keys like [Yubikey](https://www.yubico.com/) or [Solokey](https://solokeys.com/) and additionally for use of biometrics integrated in current devices (I believe Windows Hello supports this and Android offered some platform authentication capabilities too, but I think there were some additional steps in implementation of the Android version).

I believe that integrating it with this plugin would be better than doing it separately, because users could have one interface for 2FA setup and be able to set up both webauthn and code based 2FA and switch between them at login.

**Comment by julianlam** [comment]
Well, whoops :smile: I ended up implementing U2F into this plugin, although webauthn does seem like the future.

It look into it very (_very_) briefly, and it seems more complicated than U2F, even though it is supposedly compatible.
