### ISSUE TITLE
Doesn't seem to work on iOS version of Google Authenticator

### ISSUE THREAD

**Issue by timhuck** [julianlam/nodebb-plugin-2factor#5]
Possibly same issue as 

https://wordpress.org/support/topic/plugin-google-authenticator-scanning-barcode-doesnt-work

There certainly seems to be spaces / breaks in the otp URL presented as part of the error.

**Comment by julianlam** [comment]
Hm, that's quite weird, but we don't use spaces anywhere in the url. The username is slugified, and the url is space-less to begin with. We don't use the sitename...

What happens if you copy the QR code image URL and paste it into the Google Authenticator app, does it work then?

**Comment by ApfelUser** [comment]
![2factor](https://cloud.githubusercontent.com/assets/7549136/10047718/bb565676-620f-11e5-81a4-dc4c63ec3136.png)

@julianlam It isn't possible to paste the image in the Google Authenticator app.

**Comment by julianlam** [comment]
@ApfelUser Want to do some experimenting for me?

In [this file](https://github.com/julianlam/nodebb-plugin-2factor/blob/master/websockets.js#L15), can you change the highlighted line to read this instead?

`var key = utils.generateUUID().toUpperCase();` and see if it works?

If not, change it to:

`var key = utils.generateUUID().replace(/-/g, '');`

... and if still not, change it to:

`var key = utils.generateUUID().toUpperCase().replace(/-/g, '');`

? :laughing:

**Comment by ApfelUser** [comment]
@julianlam Yeah, I'll do that tomorrow. I'm on my phone right now. It is 10:00 PM here, as I am from Europe. Just so that you know :D

**Comment by julianlam** [comment]
Unacceptable, do it now :laughing: 

... just kidding, have a good night :stuck_out_tongue:

**Comment by Fortifier42** [comment]
@julianlam I have the same issue - tried all 3 methods you have there (reloaded nodebb after each change) on my own forums and had no success,
![image1](https://cloud.githubusercontent.com/assets/598503/10064798/ea0a7208-62bf-11e5-98c9-07f765c00f25.PNG)

**Comment by Janus-SGN** [comment]
I found the error, but I don't have yet the solution.
Exemple :
the encodedKey = GIZTGY3GMIYGM2LEMI8TOLJUHBRTCLJHMVQWMLLCMRQWKN3BMQYGKYRTGQ======

The problem is to the end : "="
The url encode tranalste it and google understand it as url parameter.

If you try without "=" at the end of the encodedKey, it works.

I don't search solution yet.
I try this solution manualy on iPhone 4 with iOS 7.1.2 and last version of Google Authenticator.

**Comment by julianlam** [comment]
Please give v1.1.2 a try :smile:

**Comment by julianlam** [comment]
These two sources contain code that remove the equal signs...
1. https://auth0.com/blog/2015/08/20/from-theory-to-practice-adding-two-factor-to-node-dot-js/
2. https://github.com/guyht/notp

**Comment by Janus-SGN** [comment]
It work :)
But I found another problem >< if the issuer contains space :s

**Comment by julianlam** [comment]
@Janus-SGN Well, that's your pull request, isn't it? :wink: Time to re-assign the fix to you!
