### ISSUE TITLE
Should admin lock out timer also reset 2fa?

### ISSUE THREAD

**Issue by psychobunny** [julianlam/nodebb-plugin-2factor#53]
Feels slightly weird to get prompted to re-login but no 2fa anyway (that said I notice a lot of sites are like this ex. DO, though not all)

The password is likely autofilled as well so it's basically an exercise in pressing a button to log back in, what's the point :P 

Some sort of `hasSolvedTFA: 30 days` kinda option in ACP maybe?

**Comment by julianlam** [comment]
This sounds familiar actually. I'd think a smoother flow would be to have the plugin bypass relogin and challenge with 2FA, since I imagine 2FA is more secure

**Comment by psychobunny** [comment]
Sounds good, just rechallenge. Pain in the ass so I'll regret asking about this a few months later, but worth doing :P
