### ISSUE TITLE
Admin panel access

### ISSUE THREAD

**Issue by Janus-SGN** [julianlam/nodebb-plugin-2factor#6]
Hello,

While the system is asking us the token, we can access to the admin panel.
Is there any way to disallow this access while the 2factor authentication is performing ?

Thank you.

**Comment by julianlam** [comment]
Oh dear, that's definitely an issue! Thanks for reporting

**Comment by julianlam** [comment]
Fixed on latest NodeBB `master` commits, thanks!

**Comment by Janus-SGN** [comment]
You're welcome ;)
