### ISSUE TITLE
Backup codes - 403

### ISSUE THREAD

**Issue by alfw** [julianlam/nodebb-plugin-2factor#8]
nodebb-plugin-2factor: 1.1.0
Nodebb : v0.8.2

When we try to generate backup codes the ajax put request is erroring with a 403 ( forbidden ).

**Comment by alfw** [comment]
Maby shuld have uncluded this. In the log file we are getting:

`21/9 07:18 [9926] - error: /forum/login/2fa/backup
 invalid csrf token
21/9 07:23 [9926] - error: /forum/login/2fa/backup
 invalid csrf token`

**Comment by julianlam** [comment]
Give v1.1.3 a try.

**Comment by alfw** [comment]
Hello, still problems.

When i press Generate Backup codes at  user/alfw/2factor this is what i get in console: 
```
PUT https://xxx.xxx.net/forum/login/2fa/backup 404 (Not Found)
```

Not sure if this is pull on resources?

**Comment by Janus-SGN** [comment]
Solution :

In file static/lib/settings.js, line 80, replace :
```javascript
$.ajax('/forum/login/2fa/backup', {
```

to 

```javascript
$.ajax('/login/2fa/backup', {
```

It works : 
![image](https://cloud.githubusercontent.com/assets/4434864/10120262/148653d6-64b3-11e5-89fc-d50099d564a5.png)

**Comment by alfw** [comment]
Yep! that fixed it, tnx! :)
